// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgro1QDYVKUvmct_eMYK0NlmvOk3l7NVA',
    appId: '1:178124191092:web:25a9b2be8fe4f469bb6821',
    messagingSenderId: '178124191092',
    projectId: 'major-project-7ecfb',
    authDomain: 'major-project-7ecfb.firebaseapp.com',
    storageBucket: 'major-project-7ecfb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoqEpoAL3Eqv4zVBtjLo2O7eeSWUA4mm4',
    appId: '1:178124191092:android:6fc802438e9788cebb6821',
    messagingSenderId: '178124191092',
    projectId: 'major-project-7ecfb',
    storageBucket: 'major-project-7ecfb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB6KC6McDVBSpMGF_E3vmjFjauK5bCNiI',
    appId: '1:178124191092:ios:8dbe80d0f7679304bb6821',
    messagingSenderId: '178124191092',
    projectId: 'major-project-7ecfb',
    storageBucket: 'major-project-7ecfb.appspot.com',
    iosBundleId: 'com.example.majorProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB6KC6McDVBSpMGF_E3vmjFjauK5bCNiI',
    appId: '1:178124191092:ios:8dbe80d0f7679304bb6821',
    messagingSenderId: '178124191092',
    projectId: 'major-project-7ecfb',
    storageBucket: 'major-project-7ecfb.appspot.com',
    iosBundleId: 'com.example.majorProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgro1QDYVKUvmct_eMYK0NlmvOk3l7NVA',
    appId: '1:178124191092:web:36b33223e9641549bb6821',
    messagingSenderId: '178124191092',
    projectId: 'major-project-7ecfb',
    authDomain: 'major-project-7ecfb.firebaseapp.com',
    storageBucket: 'major-project-7ecfb.appspot.com',
  );
}
